version: "3.4"

services:

  db:
    volumes:
       - ./data/db:/data/db

  web:
    build:
      target: development
      args:
        AUTH_ENABLED: 1
        AUTH_SCOPE: api://97a6b5bd-63fb-42c6-bb75-7e5de2394ba0/dmss
        CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
        TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
    image: web-dev
    stdin_open: true
#    volumes:
#      - ./web/packages:/code/packages
    environment:
      - NODE_ENV=development
      - DMSS_URL=http://localhost:8000
